version: '2'
services:
    postgres:
        image: postgres:alpine
        environment:
            - POSTGRES_USER=reviewboard
        volumes:
            - reviewboard-postgres:/var/lib/postgresql/data
    memcached:
        image: memcached:alpine
    reviewboard:
        env_file: .env
        image: ikatson/reviewboard:latest
        volumes:
            - ${REVIEW_BOARD_DATA_DIR}:/var/www/
        depends_on:
            - postgres
            - memcached
        environment:
            - PGHOST=postgres
            - MEMCACHED=memcached:11211
            - WAIT_FOR_POSTGRES=true
        ports:
            - 8000:8000

volumes:
    reviewboard-postgres:
        external: true
